# Generated by Django 3.1.2 on 2020-11-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201125_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='car',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='cost_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='description',
            field=models.CharField(default='', max_length=40),
        ),
    ]
