# Generated by Django 3.1.2 on 2020-12-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
