# Generated by Django 3.1.2 on 2020-12-30 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_auto_20201230_1814'),
        ('checkout', '0008_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_orders', to='cars.car'),
        ),
    ]
