# Generated by Django 3.1.2 on 2020-10-31 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='available',
        ),
        migrations.AddField(
            model_name='car',
            name='hire_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='car',
            name='hire_to',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
    ]
