# Generated by Django 3.1.2 on 2020-11-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='available',
            options={'verbose_name_plural': 'Available'},
        ),
        migrations.AddField(
            model_name='car',
            name='num_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
