# Generated by Django 3.1.2 on 2020-11-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20201107_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='hire_from',
            new_name='available_from',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='hire_to',
            new_name='available_to',
        ),
        migrations.AddField(
            model_name='car',
            name='insurance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='car',
            name='support',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.DeleteModel(
            name='Available',
        ),
    ]
