# Generated by Django 3.1.2 on 2020-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20201108_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='insurance_per_day',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='car',
            name='num_days_on_hire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='support_per_day',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
