# Generated by Django 3.1.2 on 2020-11-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20201108_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='num_days_on_hire',
            field=models.IntegerField(),
        ),
    ]
