# Generated by Django 3.1.2 on 2020-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20201109_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cost_per_day',
            field=models.IntegerField(),
        ),
    ]
