# Generated by Django 3.1.2 on 2020-11-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20201114_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='num_days_on_hire',
            new_name='num_days',
        ),
        migrations.RemoveField(
            model_name='car',
            name='insurance_per_day',
        ),
        migrations.RemoveField(
            model_name='car',
            name='support_per_day',
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_day', models.IntegerField(default=5)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_day', models.IntegerField(default=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
