# Generated by Django 3.1.2 on 2020-11-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20201125_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='num_days',
        ),
    ]
