# Generated by Django 3.1.2 on 2020-12-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20201208_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='car',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
