# Generated by Django 3.1.2 on 2020-12-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_auto_20201227_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='car',
            name='contact_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='car',
            name='contact_phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='county',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='car',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='street_address1',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='car',
            name='street_address2',
            field=models.CharField(default='', max_length=80),
        ),
    ]
