# Generated by Django 3.1.2 on 2021-01-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_auto_20201230_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
    ]
